apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "80"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-vol
          mountPath: /data
      volumes:
      - name: shared-vol
        persistentVolumeClaim:
          claimName: my-pvc
